### PR TITLE
TPM2 Software Stack Architecture Chart

### PR DESCRIPTION
**Pull request by plang1**
We created a chart for you to review and provide feedback. Let us know what you think.

### CODE REVIEW

**Comment by plang1** [comment]
ping @flihp 

Hi Phillip,  take a look at my 1st official pull request! and let me know what you think.  Thank you John Andersen helping me with this.

**Comment by flihp** [comment]
I've been horribly negligent in learning how this github.io stuff works. @AndreasFuchsSIT has been doing the heavy lifting here. Your PR has failed checks though but they're only from the DCO bot. If you click on the 'Details' link next to this there are instructions for fixing.

Something else I'd like to consider is where the source document for this png lives so that others can update the image if necessary. This is particularly important to us since the diagrams in the tpm2-tss documentation (https://github.com/tpm2-software/tpm2-tss#architectureblock-diagram) were made by my predecessor. When he left Intel he took all of the source materials with him (or deleted them) and so we have no way to update these diagrams without recreating them from scratch.

**Comment by AndreasFuchsSIT** [comment]
Some minor comments from MHO:
- I think we want to have the project names in there as well, because will leave people searching.
- The arrows of openssl and totp go from user->library, the other arrows are reversed library->user
- pkcs11 uses the tss directly; the tpm2-tools are only used for token-setup and is deemed to be using the python-bindings instead of the tpm2-tools
- Also do we want to have string top-to-bottom ? Makes it less symmetric but easier to comprehend ?

**Comment by pdxjohnny** [comment]
@flihp @AndreasFuchsSIT, @plang1 and I have updated this PR with the new mermaidjs based diagram. This is the first stab at using mermaid. Also we weren't sure about what all your commands meant Andreas please let us know if we misinterpreted or misunderstood anything.

GitHub is rendering `.svg` weird for me, so here is a png:

image

**Comment by pdxjohnny** [comment]
Notes from @tstruk : we should explain what the direction of the arrows mean. Right now we are showing arrows moving up abstraction levels, but we might also want to reverse the arrows and show that X is a dependency of Y via the arrow from Y to X. Either way we need to document what the direction of the arrow means.

**Comment by AndreasFuchsSIT** [comment]
tpm2-totp not tpm2-topt... ;-)
Also tpm2-totp should be headlined "Device to Human attestation" or something IMHO, since we don't just generate totps but use them.
I know, the name is unfortunate, but was inherited from mjg's work.

**Comment by pdxjohnny** [comment]
Notes from weekly sync:
- User Space Resource Manager talks to device TCTI
- Use some colors
- Don't use diamond shape since that imply decision 
- Can we make this autogenerate via Jekyll

**Comment by AndreasFuchsSIT** [comment]
What about this PR ?
I think a graph is a good idea. Will this be mergable ?

**Comment by pdxjohnny** [comment]
image

@AndreasFuchsSIT I updated it to look like this ^, thoughts?

**Comment by AndreasFuchsSIT** [comment]
Seems correct

**Pull request merged**
